### ISSUE TITLE
implement asset pipelining

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/pando.py#112]
cf. Rails' [asset pipeline](http://guides.rubyonrails.org/asset_pipeline.html)

Per IRC convo with @pjz, one suggestion for Aspen would be to implement this as a library that one would use in a simplate:

``` python
from aspen.assets import cat, minify
^L
files = ['first.js', 'second.js']
response.headers.set('Last-Modified', 'blahblahblah')
response.headers.set('ETag', 'deadbeef')
^L
{{ minify(cat(files)) }}
```

This strikes me as overly verbose, however, especially configuring the response headers for caching. We also need to gzip these.

I suggest we introduce a new simplate variant, the Pipeline Simplate. This would apply to *.min.js and *.min.css files and would look like this:

```
./file1.js
/path/to/file2.js
/assets/%version/file3.js
```

That's a newline-separated listing of filesystem paths. We should use / on all platforms and convert to \ transparently. Paths are relative to the location of the *.min.js file itself. Absolute paths start at the website root.

How do we support version tokens in the filename? To date I've done this by storing assets in a virtual directory. That's probably fine.

How do we vary the &lt;script&gt; elements to import the right files? How about a helper method on `website` that takes the URL path of a pipeline simplate and spits out script tags based on a `website.version` attribute?

``` html
<!doctype html>
<html>
  <head>
    {{ website.scripts('assets/%version/myapp.min.js') }}
  </head>
</html>
```

With `website.version = '1.0.1'` this would result in:

``` html
<!doctype html>
<html>
  <head>
    <script src="/assets/1.0.1/myapp.min.js"></script>
  </head>
</html>
```

And with `website.version = None`:

``` html
<!doctype html>
<html>
  <head>
    <script src="/assets/-/file1.js"></script>
    <script src="/path/to/file2.js"></script>
    <script src="/assets/-/file3.js"></script>
  </head>
</html>
```

**Comment by webmaven** [comment]
See also [Fanstatic](http://www.fanstatic.org/), [BowerStatic](https://bowerstatic.readthedocs.org), and [WebAssets](https://webassets.readthedocs.org).
