### ISSUE TITLE
Invert Request API

### ISSUE THREAD

**Issue by whit537** [AspenWeb/pando.py#222]
The current design of the verbose Request API has higher-order objects (Mappings, etc.) as the base value such as `request.line.uri.path`, with raw bytes in a `.raw` attribute. This is confusing. Rather, all objects representing a fundamental part of an HTTP message should be a bytes subclass, with higher-order objects available as attributes.

**Comment by whit537** [comment]
!m @pjz

**Comment by whit537** [comment]
Closing in favor of #526.

**Comment by whit537** [comment]
I really do like that requests print as HTTP messages. I suppose HTTP/2 mucks with that, and of course WSGI is lossy so this isn't guaranteed the same as what's on the wire.

```
(Pdb) print request
GET /~whit537/settings/close HTTP/1.1
Accept-Language: en-US,en;q=0.8
Accept-Encoding: gzip, deflate, sdch
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Host: localhost:8537
Cookie: ahoy_visitor=87efe43d-2e43-4803-a082-9705ce062475; suppress-welcome=; osf=56c22d9877ee83746f904fd4.7EcEAEMDpmAkqRGWhjN4fMlLkMU; csrftoken=xVNdM6fh7OiNZrSnJSEHRVysu35x0iit; sessionid=ntt4vvgbliviokz4jgbpmmh4u07tjaky; session=0fa6522c09d14637b86c0a6307faa216; csrf_token=MxWeKUKwpSuA6Q0shxI64faRelSpFbbe
Referer: http://localhost:8537/~whit537/settings/
Upgrade-Insecure-Requests: 1


(Pdb)
```

**Comment by whit537** [comment]
@Changaco at https://github.com/AspenWeb/pando.py/issues/357#issuecomment-245701482:

> If we have enough time we should try to take care of #222 before 1.0.

Do you have enough to go on to get started on this?

**Comment by Changaco** [comment]
> Do you have enough to go on to get started on this?

It would be useful to clarify the problem(s) we're trying to fix, and whether we're okay with making lots of breaking changes or if we should try to maintain backward compatibility wherever possible.

**Comment by whit537** [comment]
The problem is the confusion of wondering type what `request.line.uri.path` is. The suggested solution is that the names representing parts of an HTTP message always be bytes, with higher-order representations of those parts in attributes on the parts.

`request.line.uri.path` is currently a `Mapping`.

The proposal here is that `request.line.uri.path` be bytes, with `request.line.uri.path.parts` as the `Mapping`.

**Comment by Changaco** [comment]
I meant: is this issue only about fixing a small confusion, or do we actually want to completely revisit both the Request and Response APIs as the issue's title suggests?

**Comment by Changaco** [comment]
Regarding the Response class, I think we should kill the `raise Response(...)` pattern. Instead of creating new response objects everywhere, we should only use the one in the state. That would allow us to give it access to the `website` and `request` objects, and thus provide a richer API.

**Comment by whit537** [comment]
> we should only use the one in the state

So _that_ is what [`return response(400, 'xxx')`](https://github.com/AspenWeb/aspen.py/issues/27#issue-175831459) is about. ;-) That looks a lot like the WSGI API, with `request, response` instead of `environ, start_response`.

> do we actually want to completely revisit both the Request and Response APIs as the issue's title suggests?

That sounds like a deep rabbit hole. I've narrowed the scope of this ticket. :)
