### ISSUE TITLE
factor out simplates

### ISSUE THREAD

**Issue by whit537** [AspenWeb/pando.py#341]
I think we should promote simplates as their own thing. I just bought simplates.org for the purpose. Simplates are a file format for web programming. We should define a standard and release a reference implementation in Python, used by Aspen. We should get simplates supported on GitHub in [code blocks](https://help.github.com/articles/github-flavored-markdown#syntax-highlighting) and in their [Ace editor](http://ace.c9.io/#nav=higlighter).

This is a meta issue that will result in new issues. Wanted to capture the general idea.

**Comment by whit537** [comment]
On https://github.com/gratipay/aspen-python/issues/472 it sounds like @pjz has some code on this, but we may end up dropping back and trying strategy 1:

 1. Disentangle Aspen's http API from simplates without creating a new library (parallel to how we disentangled the dispatcher).
 2. Make a new library off the bat.

**Comment by pjz** [comment]
Working toward this slowly.  Some hangups I could use opinions/ideas on:

  1.Renderers are really part of simplates, but right now they're in `aspen.renderers` with simplates in `aspen.resources`.   Maybe simplates should go into `aspen.simplates` with `aspen.resources` doing the deciding whether to use simplates or a simple static resource object?  And then renderers could go in `aspen.simplate.renderers` ?

  2. Where should `website.default_renderers_by_media_type` end up?

  3. Where should `website.renderer_factories` end up? maybe simplate.renderer.factories() ?

**Comment by whit537** [comment]
1) Sounds about right.

2 and 3) Let's maybe look at Jinja2 and other templating systems. I believe they generally handle this with a `Context` object.

**Comment by whit537** [comment]
Where "this" is library configuration.

**Comment by pjz** [comment]
So:

 - [ ] Move simplates to `aspen.simplates`; make `aspen.resources` still choose between simplates and static resources.
 - [ ] Move `aspen.renderers` under `aspen.simplates`
 - [ ] Make a stub `aspen.renderers` for backwards compatibility with the renderer modules
 - [ ] Make SimplateFactory to hold config data like the renderer registry (aka `renderer_factories`) `default_renderers_by_media_type`

Sound good?

**Comment by whit537** [comment]
@pjz lgtm

!m @pjz 

P.S. I'm on vacation for a week. :] :palm_tree:

**Comment by pjz** [comment]
...be careful, I might Change The World while you're gone :)

**Comment by pjz** [comment]
All but the last checkbox there is done in #481 now.

**Comment by pjz** [comment]
...and now that's done too.  With more to come!

**Comment by pjz** [comment]
Simplates are mostly factored out now.  Happy vacation!

**Comment by whit537** [comment]
:astonished:

**Comment by pjz** [comment]
Once the current PR has landed, the next piece will be to actually factor them out into a separate repo with packaging, docs, etc. And also change all the aspen renderer modules into simplate renderer modules.  So if someone wants pystache support they'll have to install `aspen` and `simplates-pystache`.  

It would also be cool to have adapters like maybe `flask-simplates` or `django-simplates`, if there's glue code there that could be factored out.

**Comment by whit537** [comment]
> It would also be cool to have adapters like maybe `flask-simplates` or `django-simplates`

Yes! Ideally we can generate enough interest amongst the Flask and Django communities that those shims will get written by third parties.

**Comment by whit537** [comment]
What's our plan for other languages besides Python? Currently our `application/simplate` proto-specification doesn't allow for explicating the language of the first and second sections.

**Comment by whit537** [comment]
Let's use https://github.com/gratipay/simplates.org/issues to manage the "factoring out" part.

**Comment by whit537** [comment]
The scope of the `simplates.org` repo is:

 - the `application/simplate` specification
 - linking to implementations and tooling
 - marketing in general

The Python library we factor out should land at https://github.com/gratipay/simplates.py and be linked on simplates.org as the reference implementation.

**Comment by whit537** [comment]
Obvious solution would be a shebang at the top:

```simplate
#!python
[---]
[---] text/html
Greetings, program!
```

@pjz mentions this on https://github.com/gratipay/aspen-python/issues/474.

**Comment by Changaco** [comment]
Closing in favor of https://github.com/AspenWeb/salon/issues/13 and https://github.com/AspenWeb/simplates.org/issues.
