### ISSUE TITLE
move json registry into json renderer

### ISSUE THREAD

**Issue by pjz** [AspenWeb/pando.py#359]
The registry isn't really part of aspen core anymore, it's part of the json renderer, and should be there.

**Comment by pjz** [comment]
@whit537 :question:  Of course now it goes into `aspen.simplates.renderers` or maybe just `aspen.simplates`.  Maybe actually onto the new `SimplateDefaults` object.

**Comment by whit537** [comment]
Yeah, I guess we need to push the json wrapper from Aspen into Simplates. Putting it on SimplateDefaults sounds reasonable.

**Comment by Changaco** [comment]
Seems to me like this is done, the `json_` module was moved into `simplates` in Aspen.
