### ISSUE TITLE
Parse incoming JSON in POST body

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/pando.py#377]
I'm implementing a simplate to receive webhook callbacks which are `POST` requests with JSON data in the body (and `Content-Type: application/json` in the headers). Adding support for JSON in Aspen's [`Body._parse()`](https://github.com/gittip/aspen-python/blob/0.34/aspen/http/request.py#L700) function could make it slightly easier to write such simplates. What do you think ?

**Comment by ravitejabadisa** [comment]
HI i am facing an issue whe i have migrated code from my local system to AWS

RawPostDataException at /users/
You cannot access body after reading from request's data stream

It seems i can't access request.method and request.data in views.py simulteneously.
Is this specific to AWS?Do i nedd to do some specific config changes to resolve this issue?

It would be great if you can suggest some work around for this issue

**Comment by pjz** [comment]
If you meant to post this as an issue, you should open a new one, not revive one that's over a year old.  Also, you should include more detail, up to and including simplified code exemplifying  your problem.

**Comment by Changaco** [comment]
A quick web search shows that `RawPostDataException` is a Django exception.
