### ISSUE TITLE
Keep up with the PEPs

### ISSUE THREAD

**Issue by pjz** [AspenWeb/pando.py#409]
WSGI-ng is coming down the pipe, from https://github.com/python-web-sig/wsgi-ng ; worth keeping an eye on.

**Comment by whit537** [comment]
Good call. :-)

**Comment by pjz** [comment]
Email archives for the list are [here](https://mail.python.org/pipermail/web-sig/).

**Comment by whit537** [comment]
I've been keeping an eye on the GitHub repo. Both it and the mailing list are more or less moribund. Reopen/reticket if this changes.
