### ISSUE TITLE
Support Python 3.x

### ISSUE THREAD

**Issue by pjz** [AspenWeb/pando.py#493]
The world is changing.  We should change with it.

**Comment by whit537** [comment]
Need new mimeparse: https://pypi.python.org/pypi/mimeparse.

**Comment by pjz** [comment]
Did some work on this and ran into
```
...
  File "/home/pj/src/aspen-meta/aspen/aspen/http/request.py", line 144, in <module>
    class IntWithRaw(int):
TypeError: nonempty __slots__ not supported for subtype of 'int'
````

... which seems to me to be more impetus to, as #357 says, ' #222 or drop back to werkzeug?'

**Comment by pjz** [comment]
https://utcc.utoronto.ca/~cks/space/blog/python/IntSlotsPython3k

**Comment by whit537** [comment]
https://searx.me/?q=python%20subclass%20builtin%20types&categories=general

**Comment by pjz** [comment]
Known, wontfix bug: http://bugs.python.org/issue1173475

**Comment by whit537** [comment]
> (In a sense the way to deal with this issue when porting to Python 3 is simple; you just stop using __slots__ on your subclass of int. Everything works the same and your instances just take up a bit more memory.)

**Comment by whit537** [comment]
Refer to http://pythonhosted.org/six/. Either bring it in as a dependency, or copy/paste code from it into our own backcompat submodule.

**Comment by whit537** [comment]
Consider https://pypi.python.org/pypi/tox for testing multiple Python versions locally.

**Comment by whit537** [comment]
@Changaco Any interest in landing this before 1.0 in September?

**Comment by Changaco** [comment]
Yes, python3 is the next item in my TODO. Don't know when I'll get around to it, but it should be doable before 1.0.

**Comment by Changaco** [comment]
I have Pando's tests passing on python3. :-)

**Comment by whit537** [comment]
❗
