### ISSUE TITLE
look at babel to replace to_age, etc.

### ISSUE THREAD

**Issue by whit537** [AspenWeb/pando.py#494]
http://babel.pocoo.org/

**Comment by pjz** [comment]
`to_age` would be replaced by `babel.dates.format_timedelta`, right?

**Comment by whit537** [comment]
Sounds about right, ya.

**Comment by pjz** [comment]
Also, what's the etc?

**Comment by whit537** [comment]
I think on the call (#474) we had other ideas about formatting log messages. No?
