### ISSUE TITLE
consolidate exceptions into one module

### ISSUE THREAD

**Issue by whit537** [AspenWeb/pando.py#534]
Reticketed from #448. Looks like we started on this in 880440b577aa2cbf20c86e27249bac9c72de02e2, but that's by no means all of our exceptions. In #533 I backed that out while refactoring under #526. But now that I've refreshed my memory on #448, it looks like we should do the opposite, and move even more exceptions to `aspen.exceptions`. Ya?

**Comment by pjz** [comment]
:+1:

**Comment by whit537** [comment]
M'kay.
