### ISSUE TITLE
port to aspen

### ISSUE THREAD

**Issue by whit537** [AspenWeb/pando.py#548]
The plan on https://github.com/AspenWeb/salon/issues/2 is to split out an `aspen-core` package that contains simplates and dispatch. Once that's done (see #527) we should port `aspen.py` to use that.

**Comment by Changaco** [comment]
@whit537 Are you going to take this on, or should I? You're the one who knows the code best, so you might finish faster, but I can get it done too.

**Comment by whit537** [comment]
@Changaco Go for it, I may end up adding some commits during review.

**Comment by Changaco** [comment]
Tests are passing on my local `use-aspen` branch. \o/

**Comment by Changaco** [comment]
And tests are also passing on my local `pando` liberapay branch (with a few more tweaks). \o/
